### ISSUE TITLE
Deploy an embeddings based tool to production

### ISSUE THREAD

**Issue by Rabshab** [datasciencecampus/iati-partner-search#49]
Success for this would be a third radio option that would allow for a search using the embeddings approach

**Comment by nathanbegbie** [comment]
Currently blocked by #45

**Comment by nathanbegbie** [comment]
Currently, most of the code for the embeddings tool works as a script, but not really in a modular way, that fits in to the either the run time, or the pipeline process.
Some things to consider with getting this task 'done':
- are there any conflicts with the models at 'runtime'?
-- i.e. are there different models required that differ depending on which method we use (is there a conflict?)
- have tests been written?
