### ISSUE TITLE
Make full IATI raw data files easily usable

### ISSUE THREAD

**Issue by nathanbegbie** [datasciencecampus/iati-partner-search#5]
Currently, we do not have all of the descriptions easily accessible for the whole team to use.

Ideally, we would have this on an S3 bucket and this dataset would be updated periodically, as new data is released. (ticket to follow)

Try opening the .xml files in R rather than downloading, and put them in a usable format. Calum and Kevin tried to query the xml, instead try just opening as a column in a dataframe.

**Comment by kevincarolan** [comment]
Making progress; new setback. The .xml files are reading in, but  the formatting is getting messed up, screenshot attached. Will try to figure this out (meetings today and tomorrow) 
![image](https://user-images.githubusercontent.com/52956745/67768807-35959f00-fa4b-11e9-96c4-6157bc779067.png)

**Comment by kevincarolan** [comment]
List of issues of which we are currently aware. 

1) IATI ID's are not unique in the .xml. They are unique in the API.

2) The API has more records than the .xml. The API has 1,020,000 records, the .xml has 986,833

3) IATI descriptions are not unique. This makes sense in context but we should think about the impact on NLP. 

4) The API call and the .xml files have different IDs. 381,714 occur in the API but not the .xml, 330,608 occur in the .xml but not the API.
