### ISSUE TITLE
Build REST API over search functionality

### ISSUE THREAD

**Issue by Rabshab** [datasciencecampus/iati-partner-search#65]
- Allow for programatic use of the search functionality
- Talk to Rory (openAPI)

**Comment by rorads** [comment]
I recommend looking in to OpenAPI in some detail for this. It's a great way of making APIs open and self documenting, and could be really effective within ONS / DFID systems more broadly. Here are some possibly useful links to get going with.

* [OpenAPI Documentation](https://swagger.io/docs/specification/about/) (good to get started, and understand the main concepts)

* [Example raw JSON pet store spec](https://petstore.swagger.io/v2/swagger.json)

* [Same spec in side-by-side editor](https://editor.swagger.io/?_ga=2.256975755.1809332594.1574690351-428974194.1574690351)

What's really exciting about the last swagger tool in particular, is that it allows you to create a 'stub' server in a number of different languages, in which you can fill out your own logic post-hoc. This could be really useful in building our API before finishing the ML implementation.
