### ISSUE TITLE
Write tests for alternative methods that are currently untested

### ISSUE THREAD

**Issue by Rabshab** [datasciencecampus/iati-partner-search#67]
- Increase test coverage across the codebase

**Comment by nathanbegbie** [comment]
Currently, we have only written 2 tests for our code:
1) tests the default preprocessing and vectorizing
2) tests using the default preprocessing and vectorizing models with a search query

We should be making sure that we are testing the various configurations for the model. By writing the tests, we will also make sure that the code is configured in such a way that makes it usable as both a standalone step in the pipelining process and using it as a modular section of the whole process.

Test for:
- word2vec model with building model
- using a runtime query with the word2vec model
- building the embeddings model
- using the embeddings model at run time
- another test, using the preprocessed thing

Note! We should _not_ be reading and writing files during testing (for now). We want to keep things in memory.
