### ISSUE TITLE
Demo tool to stakeholders

### ISSUE THREAD

**Issue by Rabshab** [datasciencecampus/iati-partner-search#69]
Get feedback from Rory about current prototype

**Comment by rorads** [comment]
Thoughts from an initial look at the tool:

### Wishlist

* Inclusion of IATI Identifier in returned results. This this would allow for linking out to DevTracker or D-Portal, meaning that results could be easily inspected for other attributes (such as project partners, locations, etc.)
* The [reporting-org](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/reporting-org/) identifier of the activity. It's not always easy to deduce the publisher of each activity, so this would be useful to quickly aggregate if there were many results (i.e. 25% of the top 100 matched activities were published by <some-iati-publisher-x>. 
* Some numerical rating of similarity according to the algorithm used i.e. the top result would have the lowest/highest 'score'. Granted, this will be different for each algorithm - not important to normalise between them IMO, just useful to have a sense of proximity between searches in the same algorithm. For instance knowing that the 'best' result for search x is 'better' than the 'best' for search y would be useful in understanding and confidently using the results.
* Minimally, a simple JSON endpoint including the fields above, with a fairly high maximum number list. I'm imagining something like this:

```json
{
  "array": [
    {
      "iati_identifier": "XM-DAC-12345-abcde",
      "reporting_org": "XM-DAC-12345",
      "title": "Project tite text. Project title text. etc.",
      "description": "Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. etc.",
      "proximity": "0.835"
    },
    {
      "iati_identifier": "GB-COH-12345-abcde",
      "reporting_org": "XM-COH-12345",
      "title": "Project tite text. Project title text. etc.",
      "description": "Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. etc.",
      "proximity": "0.735"
    },
    {
      "iati_identifier": "XI-IATI-12345-abcde",
      "reporting_org": "XI-IATI-12345",
      "title": "Project tite text. Project title text. etc.",
      "description": "Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. Project description text. etc.",
      "proximity": "0.835"
    },
    {
      "iati_identifier": "ETC",
      "reporting_org": "etc",
      "title": "Etc.",
      "description": "Etc.",
      "proximity": "0.123"
    }
  ]
}
```

### API Discussion

The above JSON example is just a point of reference, and shouldn't supervene on discussions about API specification, but rather inform our requirements etc.
